import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '@/components/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sales App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/lumen/bootstrap.min.css"></link>
      </head>
      <body className={inter.className}>
        <Navigation/>
        <br></br>
        <div className="container p-4">
          {children}
        </div>
        </body>
    </html>
  )
}
